cdklabs/construct-hub-webapp

.projenrc.js, LICENSE, package.json
Configured author metadata ahead of publishing to npmjs.com.
=> chore: configure publishing information

.projen/tasks.json, .projenrc.js, package.json
=> chore: "dist" not created during build

.projen/deps.json, .projenrc.js, package.json, src/App.css, src/App.test.tsx, src/App.tsx, src/Home/index.tsx, src/Home/style.css, src/NotFound/index.tsx, src/Package/index.tsx, src/PackageDetails/index.tsx, src/PackageDocs/index.tsx, src/PackageDocsHome/index.tsx, src/PackageLatest/index.tsx, src/Packages/index.tsx, src/TypeDocs/index.tsx, yarn.lock
Initial routes for package pages with scope, name, and version path
params.
fix: #3
=> feat: package routing

src/components/PackageDocs/index.tsx
I've grown weary from trying to guess exactly how much time doc generation takes with the profiler. 
Added a log to make simple.
=> chore: log doc generation timing

public/index.html
This has been driving me crazy :-)
=> chore: change website title to "Construct Hub"

src/components/ChooseSubmodule/SearchInput.tsx, src/components/Form/Form.tsx, src/components/Form/index.ts, src/components/Header/Header.tsx
Same idea as #152 
This PR just implements a form primitive which adheres to Chakra's styled api. This was needed as Chakra's layout components do not properly implement `form`. We should prefer using primitives within this system over html elements as it will allow us to use style props which are theme-aware i.e `<Form bg="brand" onSubmit={onSubmit} />`.
=> feat: <Form /> component

src/components/CatalogSearch/CatalogSearchInputs.tsx, src/components/Header/SearchButton.tsx, src/views/Home/Home.tsx, src/views/Package/Package.tsx
Updates Search & Home page text. Also fixes a useEffect dependency causing unnecessary fetches
=> chore: text updates

src/components/LanguageBar/LanguageBar.stories.tsx, src/components/LanguageBar/LanguageBar.tsx
Just fixes some a11y violations on the language bar
=> chore: fix a11y for language bar

src/components/Header/Title.tsx
=> chore: remove white space in logo

src/util/url.test.ts, src/util/url.ts, src/views/Package/components/OperatorArea/OperatorArea.tsx
Fixes #205 
This PR ensures we are treating repo urls safely and also converts git ssh urls into valid hrefs
=> bug: do not crash on invalid url

src/components/NavPopover/NavPopoverContent.tsx, src/hooks/useRequest/useRequest.ts, src/views/Home/Home.tsx, src/views/NotFound/NotFound.tsx, src/views/Package/Package.tsx
Fixes #204 
Shows a 404 view if an assembly response errors (meaning it does not exist)
Can test here on this route with local server
http://localhost:3000/packages/@aws-cdk/cdk/v/0.34.1?lang=typescript
=> chore: show 404 if assembly is missing

src/App.tsx
So we can gather positive cookie consent from users
in the EU, in compliance with GDPR.
=> fix: actually initialize shortbread

src/App.tsx, src/constants/url.ts, src/views/FAQ/FAQ.tsx, src/views/FAQ/FAQItem.tsx, src/views/FAQ/FAQSection.tsx, src/views/FAQ/index.ts
This PR implements the faq page & respective components, though we haven't finalized our FAQ text, so it is using placeholder text. Additionally, no navigation has been added to this page as it isn't finished. To reach it, navigate directly to /faq
=> feat: faq-page (lorem text)

src/App.tsx, src/components/CatalogCard/CatalogCardContainer.tsx, src/components/Footer/Footer.stories.tsx, src/components/Footer/Footer.test.tsx, src/components/Footer/Footer.tsx, src/components/Footer/constants.ts, src/constants/url.ts, src/views/SiteTerms/SiteTerms.tsx, src/views/SiteTerms/index.ts
Implements the Site Terms Page
=> feat: site terms page

src/views/Package/components/OperatorArea/OperatorArea.tsx
=> chore: rephrase package ownership statement + author link

src/components/Code/Code.tsx, src/components/Code/MultiLineRenderer.tsx, src/components/CopyButton/CopyButton.tsx
Fixes https://github.com/cdklabs/construct-hub-webapp/issues/219
Just changes the heading background to a very light blue
=> chore: update code renderer colors

.projen/deps.json, .projenrc.js, package.json, src/components/Markdown/Markdown.tsx
Fixes https://github.com/cdklabs/construct-hub-webapp/issues/261
=> fix: type links are broken

src/views/Package/components/OperatorArea/OperatorArea.tsx
Updating the email address to the correct one
=> chore: update report link

src/components/DevPreviewBanner/DevPreviewBanner.tsx, src/components/Footer/constants.ts, src/components/Header/Title.tsx, src/hooks/useCatalogResults/useCatalogResults.ts, src/views/Home/Home.tsx
Fixes https://github.com/cdklabs/construct-hub-webapp/issues/269
Fixes https://github.com/cdklabs/construct-hub-webapp/issues/274
=> chore: various touchups

src/views/Package/components/UseConstruct/UseConstruct.tsx
Something about "Use Construct" feels extremely foreign to me. 
Suggestion to change, alternatives are happily accepted.
=> chore: rephrase "Use Construct"

public/index.html, src/components/CatalogCard/CatalogCard.tsx, src/components/PackageTag/PackageTag.tsx, src/components/Results/ResultsGrid.tsx, src/theme/components/Tag.ts, src/theme/components/index.ts, src/theme/foundations/index.ts, src/theme/foundations/sizes.ts
Updates the spacing of items within the search results card and
customizes the Tag component to better match design.
=> fix: search result card styling

src/views/FAQ/FAQ.tsx, src/views/FAQ/FAQItem.tsx, src/views/FAQ/FAQLink.tsx
Added content to FAQ, still need to fix the links and make we should we reference the FAQ from the menu
=> FAQ, need to fix links

.projen/deps.json, .projenrc.js, package.json, src/components/Markdown/Markdown.tsx, yarn.lock
Fixes #281 
Before:
After: (img resolving locally is unrelated)
=> feat: support emoji in markdown

src/views/PackageLatest/PackageLatest.tsx
=> fix: blank screen when package should 404

src/components/CatalogCard/CatalogCard.tsx, src/constants/keywords.ts, src/views/Package/components/PackageHeader/PackageHeader.tsx
=> feat: omit redundant keywords

src/api/config/index.ts, src/api/package/packages.ts, src/components/PackageCard/Heading.tsx, src/components/PackageCard/testIds.ts, src/views/HomeRedesign/HomeSection.tsx
Note: this PR depends on https://github.com/cdklabs/construct-hub/pull/365
Screenshot:
Using this config.json:
```
{
"featureFlags": {
"homeRedesign": true,
"searchRedesign": false
},
"featuredPackages": {
"sections": [
{
"name": "Featured packages",
"showPackages": [
{
"name": "@aws-cdk/aws-s3",
"comment": "One of the most popular AWS CDK libraries!"
},
{
"name": "@aws-cdk/aws-lambda"
},
{
"name": "@aws-cdk/aws-iam",
"comment": "Secure your constructs with safe and manageable permission boundaries."
},
{
"name": "@aws-cdk/pipelines",
"comment": "The most recently released L3 construct library from the CDK team!"
}
]
},
{
"name": "Recently updated",
"showLastUpdated": 5
}
]
}
}
```
=> feat: display editors note for curated packages

src/constants/keywords.ts, src/views/FAQ/FAQ.tsx
=> chore: ignore construct keyword

src/api/catalog-search/util.test.ts, src/api/catalog-search/util.ts, src/api/package/packages.ts, src/components/PackageCard/PackageCard.tsx, src/components/PackageLanguages/PackageLanguages.tsx
Fixes https://github.com/cdklabs/construct-hub-webapp/issues/477
=> bug: some package languages are undefined and not handled

src/components/PackageCard/Details.tsx
=> chore: rename label to Weekly downloads

src/components/SearchBar/SearchBar.tsx
=> chore: change search placeholder text

src/views/FAQ/FAQ.tsx
=> chore: remove dev preview phrasing

src/constants/links.ts
=> chore: update nav menu items

src/api/catalog-search/__snapshots__/catalog-search.test.ts.snap, src/api/catalog-search/catalog-search.ts
Fixes #644 
This work will need a bit of testing to validate as it relies on a fair amount of trial and error. Will add a better write up as I get closer to a point of completion
Note: This work is not yet ready as there are some edge cases where certain names don't match the way they should
=> feat: search relevance tuning

src/views/Package/PackageHeader/Details.tsx
=> chore: show more header items by default

src/views/Home/CDKTypeTabs.tsx
Fixes #649 
This is the last outstanding item from UI Review tasks
=> chore: remove counts for home page tabs and re-word first tab to recently updated

src/components/Markdown/Code.tsx
=> chore: decrease code snippet font size

src/constants/links.ts
=> chore: update Slack link

src/views/Home/Info.tsx
=> chore: reword C# to .NET

src/components/LanguageBar/LanguageBar.tsx
=> fix: language bar links to invalid URLs

src/views/Contribute/Contribute.tsx
=> chore: update Contribute text

src/components/LanguageBar/LanguageBar.tsx
Fixes an edge case I missed in #723
=> fix: incorrect language bar links on scoped packages

src/components/SearchBar/SearchBar.tsx
=> fix: wrong number of constructs in search bar

.github/workflows/release.yml, .projenrc.js
`dev` is the one we want to update now.
=> chore: change construct-hub trigger to `dev`

.github/CODEOWNERS
Add a temporary CODEOWNERS to enforce PR approvals
=> chore: CODEOWNERS

src/api/config/index.ts, src/api/package/packages.ts, src/api/stats/index.ts, src/views/Home/Home.tsx
=> chore: add home page fallback if catalog.json doesn't exist (#738)

src/views/Home/Categories.tsx
=> chore: updates websites category

src/views/Home/CDKTypeTabs.tsx, src/views/Home/Featured.tsx
=> feat: see all constructs CTA from Featured section

src/views/Home/Info.tsx
=> fix: typo on home page content

src/views/Package/PackageHeader/Install.tsx
=> fix: mobile install text width

src/views/Contribute/Contribute.tsx
=> chore: remove duplicate copy

public/index.html, src/constants/constructs.ts, src/views/FAQ/FAQ.tsx, src/views/Home/Home.tsx, src/views/Home/Info.tsx, src/views/Search/CDKFilter.tsx, src/views/Search/Search.tsx
Fixes #1058: change CDKTYPE_NAME_MAP [CDKType.cdktf]: "CDKTF" instead of "CDKtf"
=> fix: change `CDKtf` to `CDKTF`

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/upgrade-main.yml, .projen/deps.json, .projenrc.js, package.json, yarn.lock
=> chore: upgrade some dependencies
