cdklabs/construct-hub-webapp

src/components/LanguageBar/index.tsx
Silly mistake happened when combining separate `NAME_MAP` and `ICON_MAP` objects into a single `LANGUAGE_MAP`. Didn't realize the icons were pointing at the wrong assets 😅
=> bug: fix language bar icons

src/components/PackageDocs/index.tsx
I keep disabling the apiReference locally to speed up HMR while working on the package page. To prevent myself from making the same mistake (committing the param to false), I've added a dev-only query param to disable the apiReference.
To view a package page in dev without an api reference just add the following query param to the url: `apiRef=false`
=> feat: api reference query param

src/__fixtures__/assemblies/constructs@10.0.0/jsii.json, src/api/docgen/transpile/python.ts, src/api/docgen/transpile/transpile.ts, src/api/docgen/view/__snapshots__/documentation.test.ts.snap, src/api/docgen/view/api-reference.ts, src/api/docgen/view/class.test.ts, src/api/docgen/view/documentation.test.ts, src/api/docgen/view/documentation.ts, src/api/docgen/view/enum.test.ts, src/api/docgen/view/initializer.test.ts, src/api/docgen/view/instance-method.test.ts, src/api/docgen/view/interface.test.ts, src/api/docgen/view/parameter.test.ts, src/api/docgen/view/property.test.ts, src/api/docgen/view/static-function.test.ts, src/api/docgen/view/struct.test.ts, src/setupTests.ts
We mistakenly used `assembly.classes` for the submodule instead of `submodule.classes`, etc...
This is how it will look like after the fix:
```python
from aws_cdk import aws_eks
aws_eks.CfnCluster.ResourcesVpcConfigProperty(subnet_ids: typing.List[str], 
security_group_ids: typing.List[str] = None)
```
Also includes some refactoring to handle module name transliteration in more generic way in preparation of typescript support.
Note: I added the assembly of `aws-cdk-lib` (28M) for tests. Its big but not too bad. GitHub's limit is 100MB
=> fix(docgen): specifying a submodule results in an empty reference

src/components/PackageDocs/Body.tsx, src/components/PackageDocs/index.tsx, src/hooks/useQueryParams.ts
Updates to the url language were re-rendering the page markdown even when the markdown source was unchanged, which was causing poor performance - especially on larger markdown files. This change memoizes the markdown generation, markdown rendering, and the `useQueryParams` hook to minimize unnecessary re-renders
=> fix: package-doc rerender performance

src/components/LanguageSelection/index.tsx, src/constants/languages.ts, src/hooks/useLanguage/useLanguage.test.ts, src/hooks/useLanguage/useLanguage.ts, src/views/Package/index.tsx
This work prevents languages that have not yet been implemented from being selected via language bar or query param to prevent doc generation from erroring. This also updates `useLanguage` to always subscribe to the language query param if it is present
=> feat: supported languages only

src/api/docgen/view/documentation.test.ts, src/api/docgen/view/documentation.ts, src/components/LanguageSelection/index.tsx, src/constants/languages.ts, src/hooks/useLanguage/useLanguage.test.ts, src/hooks/useLanguage/useLanguage.ts
TypeScript support has been [added](https://github.com/cdklabs/construct-hub-webapp/pull/100) to the doc generation, this PR now adds typescript as a supported language in the language bar component. 
Also switch the default language to TypeScript.
=> feat: enable typescript lang selection

src/api/package/assemblies.ts
Low hanging fruit regarding performance. Runs requests for assembly dependencies in parallel rather than sequentially
=> feat: parallelize assembly requests

src/api/package/assemblies.ts
More low hanging fruit! Thanks to @iliapolo for pointing this one out. Even though we are parallelizing requests for dependency assemblies, we weren't accounting for the scenario where two dependencies shared a dependency, thus creating redundant requests.
I logged a pretty simple counter to measure the difference here
`iterations` = `recurse` calls
`requestsMade` = `fetch` calls
Before:
After:
=> feat: dedupe assembly requests

src/views/SearchResults/components/Results.tsx
No design whatsoever, just displaying the data.
Resolves https://github.com/cdklabs/construct-hub-webapp/issues/114
=> feat: package metadata in search results

src/api/package/assemblies.ts, src/api/package/metadata.ts
There is an extra `/` that breaks the request.
=> fix: broken fetching of assemblies and metadata

src/views/PackageLatest/PackageLatest.test.tsx, src/views/PackageLatest/index.tsx
For example: Redirects `packages/@aws-cdk/aws-eks` --> `packages/@aws-cdk/aws-eks/v/1.109.0`
As far as testing goes, there is a simple unit test to validate the url construction. I tried doing a full react rendering test but that seems a bit tricky since we need to mock a few hooks/context. @gabewomble maybe you can have a look?
In any case I think its ok for now.
Resolves https://github.com/cdklabs/construct-hub-webapp/issues/120
=> feat: redirect to latest version

src/components/OperatorArea/OperatorArea.tsx, src/views/SearchResults/components/Results.tsx
Render the complete information using the `<time>` element, instead of
losing the resolution. This additionally may make the content more
accessible to screen readers.
=> chore: render date/timestamps using the <time> element

src/components/GettingStartedDropdown/GettingStartedDropdown.tsx
This is a silly and harmless bug (which logs an error in console) from the GettingStartedDropdown. Mapped items need a key at the root jsx element, even if the element is a fragment 🙂
=> chore: fix mapped keys for <GettingStartedDropdown />

src/components/CatalogSearch/CatalogSearch.test.tsx, src/components/CatalogSearch/CatalogSearch.tsx, src/components/CatalogSearch/CatalogSearchInputs.tsx, src/components/CatalogSearch/constants.ts, src/components/CatalogSearch/index.ts, src/components/LanguageBar/LanguageBar.tsx, src/views/Package/Package.tsx, src/views/Package/components/ChooseSubmodule/ChooseSubmodule.tsx, src/views/Package/components/LanguageSelection/LanguageSelection.tsx, src/views/Package/components/PackageDetails/PackageDetails.tsx, src/views/Package/components/PackageDocs/PackageDocs.tsx, src/views/Package/components/UseConstruct/UseConstruct.tsx
This work sets up the package page to be ready for mobile nav functionality. The main change is that the language bar has been moved to the package details card, and the side nav is hidden on mobile. In a follow up, the side nav will be rendered in the mobile nav drawer.
Additionally, this PR moves the `CatalogSearchInputs` component into a separate file per [this comment](https://github.com/cdklabs/construct-hub-webapp/pull/180#discussion_r668119441)
=> chore: setting up for mobile package nav

src/api/package/packages.ts, src/components/CatalogCard/CatalogCard.tsx, src/hooks/useCatalogResults/useCatalogResults.test.ts
The `<CatalogCard />` had some risky / optimistic property access. Updates the catalog type to reflect that metadata _may_ not always be present on a package and handles it more gracefully
=> chore: fix metadata access

src/views/Package/components/OperatorArea/OperatorArea.tsx
Fixes #156 
Temporarily hiding the Dependency Dropdown as not all dependencies are available in s3
=> feat: hide dependencies for now

src/views/Package/components/OperatorArea/OperatorArea.tsx
Reverts cdklabs/construct-hub-webapp#188
Upon further discussion we've decided not to do this
=> Revert "feat: hide dependencies for now"

src/views/Package/components/OperatorArea/OperatorArea.tsx
Since the registry URL is well known, we can construct a URL on the client side.
=> feat: npm registry URL

src/views/Package/components/PackageDocs/PackageDocs.tsx
Adds a hook to `PackageDocs` to look for a hash and scroll to
corresponding target when source is rendered using `scrollIntoView`.
Additionally removes our previous hack around offsetting link elements
using `a:target:before` + `marginTop` to using `scrollMarginTop` to
prevent hash link targets from being rendered under the header.
Previously `scrollMarginTop` wasn't working because the selector used to
apply it wasn't effective. The link elements themselves need to be
targetted and the `:target` selector doesn't do this.
=> fix: initial load doesn't scroll to hash links

src/views/Package/components/ChooseSubmodule/ChooseSubmodule.test.tsx, src/views/Package/components/ChooseSubmodule/ChooseSubmodule.tsx
When a package doesn't contain submodules, we currently show the selection as disabled:
This seems un-necessary and just takes up screen space.
This PR simply hides it in such a case:
=> fix: submodule selection is visible even for packages that don't have any submodules

src/components/Markdown/Headings.tsx, src/components/Markdown/Hr.tsx, src/components/Markdown/Text.tsx, src/views/Package/components/DependencyDropdown/DependencyDropdown.tsx, src/views/Package/components/PackageDetails/PackageDetails.tsx, src/views/Package/components/PackageDocs/PackageDocs.tsx, src/views/Package/components/PackageHeader/PackageHeader.tsx
- Changes Dependency Dropdown colors to match theme
- Adds appropriate margins to markdown headings
- Adds dividers to markdown h1 & h2
- Hides the submodule box when no submodules are available (button was hidden though it's container wasn't)
- Fixes safari divider overflow issue
- Increases markdown divider width
- Reduces markdown divider margin-y
- Adjusts blockquote work-break to break entire words rather than mid-word
- Adjusts package header to only show first three non-empty keywords
=> chore: UI updates

src/components/SearchModal/SearchModal.tsx, src/views/Package/Package.tsx, src/views/Package/components/ChooseSubmodule/SearchModal.tsx, src/views/Package/components/PackageDetails/PackageDetails.tsx
Fixes #207 
- Closes search modal on search
- Moves UseConstruct button so that it isn't so greedy with space
=> bug: close search modal on search

src/views/Package/components/PackageHeader/PackageHeader.tsx
=> chore: apply word break to overflowing package header

src/api/package/packages.ts, src/components/CatalogCard/CatalogCard.tsx
When the publisher name is not an object (i.e: it is provided as a
string), it would not be rendered in the search results. This adds a
type check as appropriate to ensure the text is always rendered.
Fixes #206
=> fix: publisher name not shown on search results

.projen/deps.json, .projenrc.js, package.json, src/components/Markdown/Markdown.tsx, src/views/Package/components/PackageDocs/PackageDocs.tsx, yarn.lock
Enable remark-gfm so that all GitHub-Flag Markdown is supported,
including tables (Fixes cdklabs/construct-hub#197).
Properly sanitize all generated markdown using `rehype-sanitize`,
ensuring we do not render anything that GitHub would not.
Transform image and link URLs that are repository-relative, so that such
links are valid. These resolve to GitHub distribution points in the same
way that npmjs.com does, so this change is neutral for packages that are
not configured with a GitHub repository (Fixes cdklabs/construct-hub#198,
fixes cdklabs/construct-hub#199).
=> feat: better configure ReactMarkdown

public/index.html
The CSP restricts where scripts can be sourced from,
but is relatively lax with respects to where images
can be sourced from. It completely block frames and
objects.
Fixes  cdklabs/construct-hub-internal#40
=> chore: set explicit CSP

src/api/package/packages.ts, src/hooks/useCatalogResults/useCatalogResults.ts
Makes a lot more sense to display recently published packages first, so lets use this as a very basic sorting mechanism. 
Closes https://github.com/cdklabs/construct-hub-webapp/issues/216
=> feat: sort search result by publish date

src/App.tsx, src/components/CodePopover/CodePopover.tsx, src/views/Package/components/PackageDocs/PackageDocs.tsx
Reverts cdklabs/construct-hub-webapp#228
While I did test on multiple browsers, I did not test breakpoints thoroughly, this has caused regressions on small non-mobile breakpoints and will need to be revisited.
=> Revert "chore: safari css fixes"

src/App.tsx, src/components/CodePopover/CodePopover.tsx, src/components/ExternalLink/ExternalLink.tsx, src/components/Markdown/Text.tsx, src/components/NavPopover/NavPopoverContent.tsx, src/views/Package/components/PackageDocs/PackageDocs.tsx
This PR:
- Adds an ExternalLinkIcon to external links so that users have visual indication that a link will take them out of our site
- Fixes the reverted safari css changes
=> feat: show ExternalLinkIcon for external links

src/components/Markdown/Code.tsx, src/components/Markdown/Headings.tsx, src/components/Markdown/List.tsx
This PR fixes:
- List items were not aligned with the text (they appeared more on the left). This was solved by removing any explicit margin definitions and letting the markdown component handle it.
- Headings which were formatted with `pre` (i.e properties/parameters) received a smaller font size than their appropriate h-level since this is what the `Code` element does. Resolve by applying special CSS selector to override this behavior. Also changed to color to black and reserve blue colors to links only.
- Increase grey background for those headings to create a clear distinction between them and other headings. 
- Fix list item prefixes in metadata to be *italic*, as originally intended and decrease font size of metadata.
Fixes https://github.com/cdklabs/construct-hub/issues/201
=> fix: headings are not prominent enough

src/App.tsx, src/components/Card/Card.tsx, src/components/CatalogCard/CatalogCardContainer.tsx, src/components/DevPreviewBanner/DevPreviewBanner.tsx, src/components/DevPreviewBanner/index.ts, src/components/Header/Header.tsx, src/components/Markdown/Headings.tsx, src/components/Markdown/Hr.tsx, src/components/Markdown/Markdown.tsx, src/views/Home/Home.tsx, src/views/Package/components/PackageDocs/PackageDocs.tsx, src/views/Package/components/PackageDocsError/PackageDocsError.tsx, src/views/SearchResults/SearchResults.tsx, src/views/SearchResults/components/PageControls.tsx
Fixes https://github.com/cdklabs/construct-hub-webapp/issues/238
This PR implements a dismiss-able banner to indicate the application is in Dev Preview. The dismissal lasts for the duration of a session via the SessionStorage API
Additional Changes:
- Enforces consistent layout spacing on pages
- Card border & shadow updated to further match design
- Documentation borders & dividers match design colors
- Headings in markdown have addition top margin (except first)
- Adjusted Heading layout to prevent word-break on logo for tablets
=> feat: Dev Preview Banner + card adjustments

src/components/Code/MultiLineRenderer.tsx
Prevents code samples from wrapping code on safari (without breaking the functional browsers 😛 )
=> bug: safari wraps code

src/components/NavTree/NavTree.tsx, src/views/Package/components/PackageDocs/PackageDocs.tsx
Updates the Nav Tree to:
- Not cut off outlines for top & bottom elements
- Align children with their parent text rather than indent
=> chore: nav tree ui updates

src/views/Package/components/PackageDetails/PackageDetails.tsx, src/views/Package/components/UseConstruct/UseConstruct.tsx
Problem was that the package name was not correct since it wasn't taken from the `targets` in the assembly, but rather just assumed the TS module name corresponds to the python package name.
=> fix: python installation instructions are wrong

src/components/CatalogCard/CatalogCard.tsx
In the result cards, clicking on the author will now result in a search query for that author, instead of going to the author UR, which will now only be available from the operator area of the package page. 
Closes https://github.com/cdklabs/construct-hub-webapp/issues/271
=> feat: search by author

src/components/Markdown/Markdown.tsx
An example would be: https://constructs.dev/packages/cdk-iam-floyd/v/0.218.0
This PR puts a hard limit of 1MB on the size of the docs page, anything above that will cause only the README to be displayed, along with a notice that the API reference couldn't be rendered. 
Note that the README displayed is the transliterated README, so at least we have that added value for those packages. 
This is just a stop-gap until we are able to resolve the issue, but at least we won't crash and stall browsers.
=> fix: long api references do not load

src/api/package/util.ts, src/views/Package/components/DependencyDropdown/DependencyDropdown.tsx, src/views/PackageLatest/PackageLatest.test.tsx, src/views/PackageLatest/PackageLatest.tsx
Dependency links didn't remove the `^` from the version number. Now we sanitize the version string and removing any leading `^` or `~`. 
In addition, now that we have multiple major versions (this was actually true before as well) - the package latest redirection was broken for those package. Now it will redirect to the latest major version.
=> fix: dependency links are broken

src/components/Code/Code.tsx, src/components/Markdown/Headings.tsx, src/components/Markdown/Hr.tsx, src/components/Markdown/List.tsx, src/components/Markdown/Markdown.tsx, src/components/Markdown/Table.tsx, src/components/NavTree/NavTree.tsx, src/views/Package/components/PackageDocs/PackageDocs.tsx
Updates:
- H1-H3 in markdown have a divider under them
- Line heights for markdown text increased
- Divider spacing increased
- Nav Tree items line height increased
- Nav Tree links have hover state
=> feat: doc styles

src/components/ExternalLink/ExternalLink.tsx, src/components/NavPopover/NavPopoverContent.tsx, src/constants/links.ts, src/contexts/Analytics/Analytics.tsx
Fixes #315
Fixes #321 
This PR updates the FAQ link to point to /faq rather than constructs.dev/faq as well as preventing it from opening new tab. Additionally, a quick fix to our analytics handler was made to prevent page crashing with certain adblock filters
=> chore: Faq link shouldnt be external

src/views/FAQ/FAQ.tsx
I think the keyword is supposed to be `aws-cdk`, not `awscdk`.
=> docs(faq): fix keywords explanation

.projen/tasks.json, .projenrc.js, package.json
Add packaging step back into release workflow so publish to npm isn't
broken.
This was initially removed because we are pushing the src code in the
npm tarball in addition to the build output to allow build time
configuration if needed, but the projen release workflow relies on the
output of the packaging step and can't publish succesfully without it.
Fixes #
=> fix: packaging

src/components/Markdown/Table.tsx
=> fix: table width issue in md

src/components/CatalogCard/CatalogCard.tsx, src/components/PackageTag/PackageTag.tsx
=> fix: catalog card tags zIndex too high

src/views/Package/components/PackageDocs/PackageDocs.tsx
Fixes #344 
This change updates the nav item parsing function to look at an element's innerText rather than it's dataset.headingTitle
Before:
After:
=> fix: navigation items with backticks dont render properly

src/components/ExternalLink/ExternalLink.tsx, src/contexts/ExternalLinkWarning/ExternalLinkWarningModal.tsx
Fixes #361 
This PR adds the `nofollow` annotation to outgoing links which are user generated
=> feat: add nofollow to user generated links

.gitignore, .npmignore, .projen/tasks.json, .projenrc.js
Another attempt at fixing bundle content to include the build file. Verified that running `yarn build && yarn package` results in a tarball with the expected build directory.
Fixes #
=> fix: revert .projenrc to before build time config

src/App.tsx, src/components/LazyRoute/LazyRoute.tsx, src/components/LazyRoute/index.ts, src/components/PageLoader/PageLoader.tsx, src/components/PageLoader/index.ts, src/views/FAQ/index.ts, src/views/Home/index.ts, src/views/NotFound/index.ts, src/views/Package/index.ts, src/views/PackageLatest/index.ts, src/views/Packages/index.ts, src/views/SearchResults/index.ts, src/views/SiteTerms/index.ts
This work is done in anticipation of a few redesigns, but also has benefits independent of the upcoming redesign work.
When pages load now, only the code for the requested view will be downloaded to the client. This means:
- Smaller initial bundle size as we are no longer downloading every page's code on on first load
- Features which are not enabled will not be sent to the client
=> feat: Lazy Load Pages

.github/workflows/build.yml, .projen/deps.json, .projen/tasks.json, .projenrc.js, cypress.json, package.json, proxy.js, src/lib/shortbread/shortbread.ts, yarn.lock
This PR implements a simple SPA server with proxying to our deployment which helps achieve the following:
1. Testing prod webapp builds locally
2. Faster E2E runtimes in CI, meaning less flakiness & quicker builds (to be verified). This is because we previously needed to run a dev server which is a much less optimized bundle
=> feat: proxy server for local + ci builds

.projen/tasks.json, .projenrc.js, package.json, src/__fixtures__/catalog.json, src/api/catalog-search/__snapshots__/catalog-search.test.ts.snap, src/api/catalog-search/__snapshots__/util.test.ts.snap, src/api/package/packages.ts, src/components/CatalogCard/CatalogCard.tsx, src/hooks/useCatalogResults/useCatalogResults.test.ts
I found a surprising bug when testing the website against my updated instance of the Construct Hub, where the home page simply went blank because of an error "w.keywords is undefined" coming from CatalogCard.tsx. This is caused because packages are now ingested on the backend even if they might not have CDK keywords (https://github.com/cdklabs/construct-hub/pull/330), so the "keywords" field may be null. This fixes the error by changing the type of keywords to possibly be undefined.
I also added a projen task for updating snapshots, as well as a package to the catalog.json fixture so that we have a reference example of packages without any keywords.
=> fix: home page not rendering when package has no keywords

src/views/Package/Package.tsx
Improves the user experience by showing a loading spinner when you are switching between languages (for some docs, this can take multiple seconds). The existing experience is that a loading spinner only appears when you load the page for the first time.
Screenshot:
=> fix: show loading spinner when switching languages

src/views/FAQ/FAQ.tsx
the phrase "which is a TypeScript-based" appeared twice in a row
=> remove duplicate text in FAQ

src/service-worker.ts
Should fix #512
Updating caching policies implemented by our service worker which is being used to support PWA functionality such as using the website offline.
Currently, if the user has visited the website previously but they have old data cached, the service worker will request data "from both the cache and the network in parallel" per the `StaleWhileRevalidate` policy. This will update the cache with the newest data, but this data will only be served on subsequent responses, which explains existing behavior where the user only sees new data after a refresh.
This PR changes updates the service worker so that dynamic data sources such as the package catalog will first attempt to return the response from the network, and only fall back to the cache if no response is received. In doing so …
=> chore: fetch package data from network instead of cache by default

cypress/integration/home.spec.ts, src/views/HomeRedesign/CDKTypeTabs.tsx, src/views/HomeRedesign/Info.tsx
Updates the default search sort for several links on the home page. Now all links default to sorting by # of downloads, except for the "See all constructs" link (when no CDK type or filter is specified), which will default to sorting by newest.
=> fix: default sorts for search links on home page

src/views/Package/PackageHeader/Details.tsx
Fixes https://github.com/cdklabs/construct-hub-webapp/issues/389
Allows users to query an author name from the package page by always treating the author name as a link to search results for that author
=> feat: search by author from package page

cypress/integration/header.spec.ts, src/components/Header/MobileNav.tsx, src/components/Header/MobileNavLinks.tsx
Fixes #482
Re-implements the mobile nav links to be displayed in an accordion which is open by default. This prevents the need to open a popover, which is a poor experience for mobile. Additionally, it allows sections to be collapsed
=> feat: improved mobile nav UX

cypress/integration/home.spec.ts, src/views/SearchRedesign/CDKFilter.tsx, src/views/SearchRedesign/FilterHeading.tsx, src/views/SearchRedesign/LanguageFilter.tsx
Fixes #600 
Fixes #590 
Fixes #591 
Note: For the purpose of the screenshot I hard-coded the tooltips to be open by default. Additionally, the hint for the `Publisher` (currently phrased as Author) group will require a backend feature
*The typo in the language popover `foruse` has been fixed*
=> feat: Review: Search Page

src/api/catalog-search/catalog-search.ts, src/api/package/packages.ts
We have a probe package that gets a new version published every 3 hours,
and we don't want this to pollute search results, or steal a "recently
updated" slot away from a more deserving package...
We are hence registering the `construct-hub/hide-from-search` keyword
on such packages, which should effectively cause the package to never
be shown on search results, or in the "what's new" section.
=> chore: shadow-ban packages with a specific keyword

src/hooks/useHistoryState/index.ts, src/hooks/useHistoryState/useHistoryState.ts, src/views/Home/CDKTypeTabs.tsx
Previously, there was a UX bug where the user could select a CDK type tab on the home page, click on a package card, navigate back, and then the tab they had selected would be reset. This fixes the bug by associating the tab state with the navigation history.
=> fix: CDK type tab state not remembered

.projen/deps.json, .projen/tasks.json, .projenrc.js, package.json, src/theme/index.ts, yarn.lock
The latest version of chakra-ui breaks any configuration for color mode in chakra and always forces the system theme.
Our dependency upgrade workflow introduced this version and has caused visual issues for multiple users. Pinning the version should solve this for the time being until chakra-ui fixes the issue on their end
Here's a link to the @chakra-ui issue: https://github.com/chakra-ui/chakra-ui/issues/4987
=> bug: lock chakra version to fix dark mode bug

.projen/tasks.json, .projenrc.js
Following #617 it appears the packaging step is now being called twice - this fixes so that packaging is performed at the very end of the build.
=> chore: remove duplicate packaging step

.projen/tasks.json, .projenrc.js, package.json, src/no-op-sw.js
In #571 we updated the default JavaScript code to try and unregister service workers. However, the same service-worker.js file is still being served at the root of the website, which may cause browsers that still have the old service worker installed to think there has been no changes to the service worker, so it may continue serving old cached content. A more proper fix as described by [this Stackoverflow post](https://stackoverflow.com/questions/33986976/how-can-i-remove-a-buggy-service-worker-or-implement-a-kill-switch/38980776) is to replace the service worker with a no-op worker that does not try serving any cached content.
=> fix: replace service worker with no-op worker

src/theme/components/Checkbox.ts, src/theme/components/Radio.ts, src/theme/components/index.ts, src/views/SearchRedesign/CheckboxFilter.tsx, src/views/SearchRedesign/FilterHeading.tsx, src/views/SearchRedesign/FilterPanel.tsx, src/views/SearchRedesign/RadioFilter.tsx
Implements the following changes:
- Ensure all spaces between filter groups = 16px
- Ensure all spaces between filter label and filter values = 8px
- reduce radio buttons and checkboxes to have size 14x14px
- space between radio buttons and checkboxes = 4px
- Modify question mark icon size from 16x16 to 14x14
- Reduce spacing between tooltip icon and label to 6px
=> chore: filter ux adjustments

src/views/SearchRedesign/SearchDetails.tsx, src/views/SearchRedesign/SearchResults.tsx
Fixes #588 
Fixes #587 
Implements the following changes:
- When there is only a single page of results, display "Showing **x** of **x** results"
- Scroll to top when search results change
- When there are no results, display "There were no results for **X**. Try a different term."
=> chore: search label adjustments

src/views/Package/FeedbackLinks.tsx
Fixes #648
The feedback links on the bottom of the package page were not wrapping on mobile, causing overflow issues
=> fix: broken overflow on mobile

src/views/Package/util.test.ts, src/views/Package/util.ts
If a line within a fenced code block in a markdown document begins with `#`, then our parsing would mistakenly identify it as a header. Prevent that from occurring by parsing out fenced code blocks before parsing out header lines.
NOTE: currently does not support [indented or "unfenced" code blocks](https://github.github.com/gfm/#indented-code-blocks).
=> fix: md code blocks breaking navigation

src/views/Package/DependenciesList.tsx, src/views/Package/PackageHeader/Heading.tsx
Fixes #638
Displays dependency versions in the same manner as we did previously within the dropdown. Also recolors the package version from a blue (commonly used in links) to prevent confusion
=> feat: show dependency versions

src/components/Code/Code.tsx, src/components/Markdown/Code.tsx, src/views/Package/PackageHeader/HeaderContainer.tsx, src/views/Package/PackageHeader/Heading.tsx
Fixes https://github.com/cdklabs/construct-hub/issues/538
We can now display more keywords on the package header! This is using flex gap which is supported on Firefox, Chrome, and Safari meaning we don't have to hack a solution when items wrap
=> feat: show all keywords on package page

src/api/catalog-search/__snapshots__/catalog-search.test.ts.snap, src/api/catalog-search/catalog-search.ts, src/components/SearchBar/SearchBar.tsx, src/views/SearchRedesign/SearchResults.tsx
Fixes #666 
Adds tags to search indexing. Also updates the catalog estimate in the search placeholder to round down, and resets sorting to relevance when a user types a new input
=> feat: add tags to search indexing

src/views/Package/PackageState.tsx, src/views/Package/util.test.ts, src/views/Package/util.ts
Add a `submodule=` query parameter if navigation item is within a submodule.
Fixes #692
=> fix: nav items broken for submodules

src/api/package/assembly.ts
Since backend now trims down some fields in `assembly.json`, it would be wise to reflect that in the downstream types so that client code won't accidentally use these fields in the future.
=> chore: improve assembly type safety

src/views/Package/util.test.ts, src/views/Package/util.ts
1. Remove trailing ":" or "." from navigation bar titles.
2. If the README nav tree has a single root, collapse it into the "Readme" item to reduce redundant nesting.
Before:
After:
=> feat: readme ui tweaks

src/views/Package/PackageDocs.tsx, src/views/Package/PackageTypeDocs.tsx
When clicking on a nav item from readme, it will scroll the view so that this item is at the top (which implies that the package header is not displayed). When clicking on an API reference item, it will scroll to 0 (which implies that package header is displayed). This results in an inconsistent exprience.
To solve this, we added an `id` to the API doc header and scroll it to view if the URL is an `/api` URL.
Additionally, we also made this header a link, so that it will behave like README headers (which are links to themselves).
=> fix: api ref nav behaves differently from readme

src/components/Markdown/Markdown.tsx
Fixes #290
Images were not rendered correctly because they our code assumed that the images that were referenced as "relative" were at the root of their repository. This has been updated to now take into account the subdirectory, so that all images in `@aws-solutions-constructs/` libraries are displayed.
=> fix: broken README images for some construct libraries

cypress/integration/home.spec.ts, src/api/config/index.ts, src/components/DevPreviewBanner/DevPreviewBanner.tsx, src/contexts/Config/Config.tsx, src/views/Home/Home.tsx
Remove a few sections from the home page for and introduce a feature flag `fullSite` which offers the full experience.
Also, now feature flags can be enabled using query params (e.g `?ff-fullSite`).
=> feat: minimal home page

src/components/PackageCard/Tags.tsx, src/components/PackageTag/PackageTag.tsx, src/util/package.test.ts, src/util/package.ts, src/views/Home/Categories.tsx, src/views/Package/PackageHeader/Heading.tsx, src/views/SearchRedesign/KeywordsFilter.tsx
Fixes #718 
Updates the home page categories. Also fixes a bug where clicking on tags on cards would apply a filter with no way to remove the filter.
=> chore: update home page categories, fixes tag click bug

src/components/SearchBar/SearchBar.tsx
Fixes the search icon on the search results page and on the header of package pages to be clickable.
=> fix: search icon is not clickable

src/views/Package/PackageDocs.tsx
Currently, visiting a page like https://constructs.dev/packages/@aws-cdk/aws-s3/v/1.132.0/api displays a page with no content (fortunately there is still a sidebar you can navigate to).
Since we do not have anything to show for this URL right now, we should just redirect the user to the root docs page.
=> fix: visiting /api renders empty page

src/views/SearchRedesign/SortAndFilterDrawer.tsx
Fixes #720 
I think every web developer has had to fix this issue in some way before. Mobile browsers don't include the address bar height as part of their `vh` calculation (for justifiable reasons) which can cause some annoying issues for applications that use `vh` units. Fortunately, we can solve this issue by setting a max height of 100% on the filter drawer that will prevent the close button from being hidden under the address bar
=> fix: mobile filters dont account for address bar in calculated height

.github/workflows/release.yml, .projenrc.js
Cherry-pick of https://github.com/cdklabs/construct-hub-webapp/pull/753 to `main`
=> chore: change construct-hub trigger to `dev`

.github/workflows/release.yml, .projenrc.js
Now that CH `main` upgrade workflow [only upgrades the webapp](https://github.com/cdklabs/construct-hub/pull/607), its ok for a webapp release to trigger it.
=> chore: trigger ch main upgrade on release

.github/workflows/release.yml, .projenrc.js, README.md
Cherry-pick https://github.com/cdklabs/construct-hub-webapp/pull/757 to `main`
=> chore: trigger ch main on release

src/components/CDKType/CDKType.tsx, src/components/Page/Page.tsx, src/lib/shortbread/shortbread.ts
The ShortBread initializatio code is registered in a `window.load` event
handler, however it appears that event has already fired in WebKit-like
browsers when the event handler is added.
Just initialize ShortBread in-band instead, so it always shows.
Additionally - adjusted to dev-mode CSP to match the production site's
with the required adjustments (dev-mode is served over HTTP, and so most
of the sources are also HTTP instead of HTTPS like on production).
Also, fixed a React warning pertaining to a `forwardRef` use.
=> fix(shortbread): cookie consent not showing on Safari, Chrome

src/components/CDKType/CDKType.tsx, src/components/Page/Page.tsx, src/lib/shortbread/shortbread.ts
The ShortBread initializatio code is registered in a `window.load` event
handler, however it appears that event has already fired in WebKit-like
browsers when the event handler is added.
Just initialize ShortBread in-band instead, so it always shows.
Additionally - adjusted to dev-mode CSP to match the production site's
with the required adjustments (dev-mode is served over HTTP, and so most
of the sources are also HTTP instead of HTTPS like on production).
Also, fixed a React warning pertaining to a `forwardRef` use.
=> fix(shortbread): cookie consent not showing on Safari, Chrome (#776)

src/components/SearchBar/SearchBar.tsx, src/views/Home/Categories.tsx
Fixes #796 
Adds outlines to use case buttons and search bar
=> fix: adds focus outlines to usecase buttons and search bar

src/components/Code/MultiLineRenderer.tsx
=> fix: overflow on code blocks for safari

src/components/Markdown/Headings.tsx, src/components/NavTree/NavTree.tsx, src/views/Package/PackageDocs.tsx
Fixes #736 
Since we cannot guarantee that markdown headers will start with a letter, we can't query select markdown headings by their id. Instead, we can use the `data-heading-id` attribute and maintain the same functionality while preventing an error from querying invalid id's.
Additionally, this work fixes the Nav Item active states so that the active nav item will be colored blue - which was prior behavior to the markdown rendering changes from @MrArnoldPalmer
To test this work, I had to download a markdown response for a package, and copy it to my public folder with the corresponding request path (`localhost:3000/data/foo/v123/docs-typescript.md` => `public/data/foo/v123/docs-typescript.md`). This allowed me to modify the markdown headings freely for testing as the original library …
=> fix: support nav items which do not start with letters, reimplement active nav item state

cypress/integration/home.spec.ts, src/views/Home/CDKTypeTabs.tsx
Currently the CDK type tabs are showing no packages (or simply outdated packages) because of a change made in our backend to the CDK type tag IDs. This fixes the tag IDs so the correct packages are displayed.
=> fix: CDK type tabs displaying no packages

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/upgrade-main.yml, .projenrc.js
The current node version we are using the workflows is causing the upgrade workflow to [fail](https://github.com/cdklabs/construct-hub-webapp/runs/4629550219?check_suite_focus=true):
```console
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
child_process.js:674
throw err;
^
Error: Command failed: yarn install --check-files
error @typescript-eslint/eslint-plugin@5.8.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "12.20.0"
error Found incompatible module.
```
This corresponds to our configuration in [construct-hub](https://github.com/cdklabs/construct-hub/blob/main/.projenrc.js#L87).
=> chore: bump node version in workflows

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/upgrade-main.yml, .mergify.yml, .projenrc.js, package.json, yarn.lock
Our `e2e` wasn't configured in mergify to enforce it passes before merge. 
Fortunately it **is** configured as a GitHub required status check, but lets also add it to mergify.
=> chore: mergify to enforce e2e tests

src/views/Contribute/Contribute.tsx
Add extra information to help construct library authors debug issues with their libraries not appearing on Construct Hub.
=> chore: improve FAQ content

src/views/Package/PackageDocs.tsx
Fixes https://github.com/cdklabs/construct-hub/issues/718
When switching tabs or windows on a package page, the page scrolls back to top when it takes focus.
1. User scrolls down package docs
2. User switches tabs / window
3. User returns to package docs, scroll state should persist.
Verifiable here - https://constructs.dev
1. User scrolls down package docs
2. User switches tabs / window
3. User returns to package docs, scroll state resets to top of page.
=> fix: package page scrolls to top on focus

src/util/url.test.ts, src/util/url.ts, src/views/Package/PackageHeader/SelectVersion.tsx
Fixes #869 
When changing package versions, the page should persist the current readme segment or api reference page
1. User selects an api reference page
2. User changes package version
3. Api reference page should remain, version should update
1. User selects an api reference page
2. User changes package version
3. Version updates but the page reverts to showing the readme
=> fix: Persist api reference on version change

public/index.html, scripts/proxy-server.js
This pull request updates the webapp index.html to point to the new `preload.js` file rather than hard-coding the scripts in our public library. This will allow Construct Hub operators to define and use their own preload scripts, which can serve as an entry point for monitoring or analytics.
1. `git fetch && git checkout feat/preload-script`
2. `yarn && yarn dev`
3. Open the network tab, verify that `preload.js` loads and that analytic calls are made by filtering `b/ss`
=> feat: support preload script

src/components/NavTree/NavTree.tsx, src/views/Package/PackageDocs.tsx
Updates the table of contents so that it always has the same width on desktop viewports, as it can seem overly large or overly squished on certain screen resolutions.
Also updates the table of contents to display ellipses when titles get too long -- the CSS for ellipses was already there, but the text was still wrapping since the `white-space` property wasn't set to `nowrap`.
=> chore: update TOC to be fixed width

src/App.tsx, src/constants/url.ts, src/views/Random/Random.tsx, src/views/Random/index.ts
Visit constructs.dev/random (or your-construct-hub.com/random) to get taken to a random construct.
This is something I thought would be useful for testing purposes so that I can easily visit a random package to see how the API reference looks, whether tags are appearing properly, etc. By contrast if I find packages through search, I tend to be biased towards packages that are recently published, or are ranked highest/lowest in downloads, or come at the beginning/end of the alphabet, etc.
For now this is just an easter egg basically, but I'm totally open to adding it to the UI. 🙂
=> feat: add random package route

src/views/Package/LanguageBar.tsx
Reverts the changes from #723 since the Construct Hub backend now generates IDs / urls that are stable across languages when applicable (https://github.com/cdklabs/construct-hub/issues/142). More precisely, when a linked section of a page has docs in multiple languages, the corresponding directory and URL hash should be the same across them (`/api/Foo#bar`).
Fixes #714
=> fix: API reference resets when switching languages

src/components/Markdown/Text.tsx
Fixes #892 by changing all non-external links to implicitly get treated as internal navigation links.
=> fix: links within API reference take longer to load

.gitignore, .npmignore, .projenrc.js, .vscode/settings.json, src/components/Markdown/Headings.tsx, src/views/Package/PackageDocs.tsx
Fixes #867 
Separates the anchor element from the markdown heading to make it easier to copy headings.
When hovering the header line, the link icon will become visible. It will remain visible if clicked / focused
=> feat: separate link from markdown heading

.github/workflows/e2e-canary.yml, .github/workflows/integ.yml, .projenrc.js
1. Run canary tests every 30 minutes instead of 3 hours
2. Add debug flags to investigate why cypress workflow takes longer sometimes
=> ci: run canary tests every 30 minutes

src/constants/languages.ts, src/hooks/useLanguage/useLanguage.test.ts, src/util/url.test.ts
Adds go to supported languages array so packages with generated Go
documentation will show Go in their languages list.
Fix: #953
=> feat: add go support

src/views/Package/PackageHeader/Install.tsx
Fixes missing install instructions for go packages.
Screenshot:
=> fix: missing go install instructions

src/api/config/index.ts, src/components/Page/Page.tsx
This change adds link tag in the frontend to support RSS/ATOM feeds for latest packages. 
re: https://github.com/cdklabs/construct-hub/pull/855/
=> feat: add support for RSS/ATOM feed

.github/workflows/e2e-canary.yml, .github/workflows/integ.yml, .projenrc.js
Ideally there should be some way to have this self-managed by projen, though I haven't thought of what the best way to do this is yet. Ref: https://github.com/projen/projen/issues/1844
The main reason I'm submitting this is to see if perhaps upgrading the cypress actions version might resolve the weird time variance we have in our e2e-canary tests: https://github.com/cdklabs/construct-hub-webapp/actions/workflows/e2e-canary.yml
=> chore: upgrade GitHub actions versions

src/views/Package/ShareInfo.tsx
Accidentally hard-coded the link to the package.
=> fix: badge always links to constructs

public/badge-dark.svg, public/badge-dynamic.svg, public/badge-light.svg
On Safari, our Construct Hub badge SVG has a coloring issue:
After some googling I initially thought this was caused by a bug in WebKit (https://bugs.webkit.org/show_bug.cgi?id=199134) -- but after diving a little deeper, it turns out this is caused by an erroneous line of code in the SVG. In Chrome/Firefox it seems that this erroneous line doesn't make a difference, but in Safari it causes coloring issues.
For consistency I've also updated the non-dynamically-colored SVGs with the same fix.
=> fix: badge color broken in safari

src/views/Home/Info.tsx, src/views/Home/InfoSection.tsx
Fixes info column layout on the home page where content overflows at around 1280px breakpoint.
Fixes https://github.com/cdklabs/construct-hub/issues/973
=> fix: layout bug on home page

.projenrc.js, package.json, yarn.lock
The upgrade workflow is currently failing with this error message.
```
warning Pattern ["wrap-ansi-cjs@npm:wrap-ansi@^7.0.0"] is trying to unpack in the same destination "/home/hallcor/.cache/yarn/v6/npm-wrap-ansi-cjs-7.0.0-67e145cff510a6a6984bdf1152911d69d2eb9e43-integrity/node_modules/wrap-ansi-cjs" as pattern ["wrap-ansi@^7.0.0"]. This could result in non-deterministic behavior, skipping.
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: /home/hallcor/work/cdklabs/construct-hub-webapp/main/node_modules/cypress
Output:
/home/hallcor/work/cdklabs/construct-hub-webapp/main/node_modules/listr2/dist/renderer/default.renderer.js:7
const cliWrap = require("wrap-ansi");
^
Error [ERR_REQUIRE_ESM]: require() of ES Module …
```
=> chore: fix upgrade workflow

.github/workflows/e2e-canary.yml, .github/workflows/integ.yml, .projenrc.ts
v3 is deprecated and github actions choke.
=> chore(deps): upgrade to v4 of actions/upload-artifact and actions/download-artifact
